Schrijf ontwerp theorie
RolfHut/Design-Engineering-voor-Fysici-Dictaat pull request #3
Opened 2024-05-07 12:13 UTC by RolfHut

Ik heb ontwerptheorie opgeschreven. Graag review voor goedkeuren:

- mist er nog iets?
- overduidelijke fouten?

Zodra review ok, merge ik het in pre-release.

2024-05-08 10:28 UTC, Tijnth requested changes
Een paar puntjes die opvallen:

- Spelfouten zijn gelijk verbeterd en gepushed in deze branch
- Kunnen we 'activiteit' aan het begin van de tekst aanpassen naar 'ontwerpstap'? Ik denk dat dat wat duidelijker zou zijn. Maar misschien was dit wel een bewuste keuze, dus heb het laten staan voor nu.
- Is een korte caption of beschrijving bij het figuur handig? We refereren aan het begin van de tekst naar ontwerpstappen die nog niet eerder besproken zijn in de tekst.
- Criteria opstellen is deel van de analyse stap. In de tekst staat dit nu als een aparte stap, maar ik dit dat het heel belangrijk is dat we duidelijk maken dat de criteria deel uitmaken van de analyse stap.
- Kunnen we een gestructureerde lijst maken voor de analyse stap qua inhoud? Dus criteria, achtergrond fysica en relevante theorie, probleemomschrijving
- Is het handig om nog iets te zeggen over het onderscheid tussen pass-fail criteria en optimalisatie criteria? Die laten we nu niet voorbij komen.
- Kunnen we de grootte van de kopjes aanpassen om de hiërarchie van onderwerpen duidelijker te maken?: bijvoorbeeld dat de SMART kopjes kleiner zijn dan die van de ontwerpstappen 

Inhoud van het verhaal is goed en reflecteert duidelijk de stof die we toetsen.

2024-05-13 12:02 UTC, RolfHut commented
> * Spelfouten zijn gelijk verbeterd en gepushed in deze branch

thanks!

> * Kunnen we 'activiteit' aan het begin van de tekst aanpassen naar 'ontwerpstap'? Ik denk dat dat wat duidelijker zou zijn. Maar misschien was dit wel een bewuste keuze, dus heb het laten staan voor nu.

Dat is heel bewust. Extra text toegevoegd om verschil duidelijk te maken.

> * Is een korte caption of beschrijving bij het figuur handig? We refereren aan het begin van de tekst naar ontwerpstappen die nog niet eerder besproken zijn in de tekst.

gedaan

> * Criteria opstellen is deel van de analyse stap. In de tekst staat dit nu als een aparte stap, maar ik dit dat het heel belangrijk is dat we duidelijk maken dat de criteria deel uitmaken van de analyse stap.

ik wil didactisch gezien Criteria op hetzelfde niveau hebben als de andere stappen, omdat het zo'n belangrijk onderdeel is waar we een hele ontwerpopdracht aan besteden. Heb wel zin toegevoegd om dit duidelijk te maken.

> * Kunnen we een gestructureerde lijst maken voor de analyse stap qua inhoud? Dus criteria, achtergrond fysica en relevante theorie, probleemomschrijving

Daar moeten we maar eens over bomen, ik vind dat achtergrond fyisca al vaak een uitstapje naar simulatie is tijdens analyse en niet daarbinnen thuishoort.

> * Is het handig om nog iets te zeggen over het onderscheid tussen pass-fail criteria en optimalisatie criteria? Die laten we nu niet voorbij komen.

Ja, heb ik toegevoegd.

> * Kunnen we de grootte van de kopjes aanpassen om de hiërarchie van onderwerpen duidelijker te maken?: bijvoorbeeld dat de SMART kopjes kleiner zijn dan die van de ontwerpstappen

Dat waren ze al, maar verschil is te subtiel, ik heb een extra niveau aangebracht.

2024-05-15 10:00 UTC, Tijnth approved these changes

2024-05-15 10:00 UTC, MarkMelotto approved these changes

2024-05-15 10:01 UTC, merged