Intro and references
RolfHut/Design-Engineering-voor-Fysici-Dictaat pull request #6
Opened 2024-05-13 14:28 UTC by RolfHut

inhoudsopgave aangepast: alleen leerdoelen, rest eruit. Referenties moeten nog.

2024-05-13 20:35 UTC, RolfHut commented
ok, dat waren een hele zooi commits. Nu klaar voor review @MarkMelotto

2024-05-15 09:34 UTC, MarkMelotto requested changes
verwijder de test referentie

2024-05-15 09:34 UTC, MarkMelotto commented on book/references.md
hier staat nog een test referentie

2024-05-15 09:44 UTC, MarkMelotto approved these changes
👍

2024-05-15 09:46 UTC, merged